In [1]:
def test():
    print('test() for function')
    return
test()

test() for function


In [2]:
class demo:
    def test(self):
        print
        ('test() ofr the class and method')
        return
obj=demo()
obj.test()

In [3]:
class demo1:
    def fact(self,n):
        #return the factorial
        fact=1
        while(n!=0):
            fact=fact*n
            n=n-1
        return fact
p1=demo1()
print(p1.fact(5))

120


In [ ]:
#method
#def test(self,para1,para2)

In [4]:
class demo2:
    a,b
    def accept(seelf,p1,p2):
        a=p1
        b=p2
        return
    def display(self):
        print('a=',a)
        print('b=',b)
c1=demo2()
c1.accept(10,20)
c1.display()

NameError: name 'a' is not defined

In [ ]:
class parrot:
    

In [6]:
class demo2:
    def __init__(self,p1,p2):
        self.p1=p1
        self.p2=p2
    def add(self,p1,p2):
        return p1+p2
c1=demo2(10,20)
print(c1.add(100,200))

300


In [1]:
#Parent Class
class Person(object):
    #constructor
    def __init__(self,name):
        self.name = name
    def getName(self):
        return self.name
    def isEmployee(self):
        return False 
    
#Derived Class 
class Employee(Person):
    def isEmployee(self):
        return True 
    
emp = Person("Anil")
print(emp.getName(),emp.isEmployee())

emp1 = Employee("Akhil")
print(emp1.getName(),emp1.isEmployee())

Anil False
Akhil True


In [2]:
lst=[1,2,3,4]
print(lst)

[1, 2, 3, 4]


In [4]:
import numpy as np
lst=[1,2,3,4]
array=np.array(lst)
print(array)

[1 2 3 4]


In [6]:
lst=[1,2,3,4]
array=np.array(lst)
print(array.shape)
print(array.dtype)

(4,)
int32


In [7]:
A=np.matrix(np.ones((4,4),dtype=np.int32))
print(A)

[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]


In [9]:
A=np.matrix(np.ones((4,4),dtype=np.int32))
np.asarray(A)[2]=5
print(A)

[[1 1 1 1]
 [1 1 1 1]
 [5 5 5 5]
 [1 1 1 1]]


In [10]:
A=np.matrix(np.ones((4,4),dtype=np.int32))
np.asarray(A)[1][3]=14
np.asarray(A)[3][3]=16
print(A)

[[ 1  1  1  1]
 [ 1  1  1 14]
 [ 1  1  1  1]
 [ 1  1  1 16]]


In [13]:
import numpy as np
np.arange(1,10)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [14]:
np.arange(1,100,9)

array([ 1, 10, 19, 28, 37, 46, 55, 64, 73, 82, 91])

In [15]:
# Indexing and Slicing of Numpy
a1 = np.array([(1,2,3),(4,5,6)])
print(a1)

[[1 2 3]
 [4 5 6]]


In [16]:
a1 = np.array([(1,2,3),(4,5,6)])
print("Second Row: ",a1[1])


Second Row:  [4 5 6]


In [17]:
a1 = np.array([(1,2,3),(4,5,6)])
print("Slicing Column :",a1[:,2])

Slicing Column : [3 6]


In [18]:
a1 = np.array([(1,2,3),(4,5,6)])
print("Row and Column",a1[1,:1])

Row and Column [4]


In [19]:
a1 = np.array([(1,2,3),(4,5,6)])
print("First Row :",a1[0])

First Row : [1 2 3]


In [20]:
a1 = np.array([(1,2,3),(4,5,6)])
print("First Row :",a1[0])

First Row : [1 2 3]


In [21]:
a1 = np.array([(1,2,3),(4,5,6)])
print("Slicing Column :",a1[:,1])

Slicing Column : [2 5]


In [22]:
a1 = np.array([(1,2,3),(4,5,6)])
print("Slicing Last Column :",a1[:,2])

Slicing Last Column : [3 6]


In [23]:
a1 = np.random.normal(5,1,10)
print(a1)

[7.24792511 4.29721562 5.49338629 4.94275269 5.85951491 4.88347679
 4.99489698 3.74287264 3.29102549 5.46055683]


In [24]:
# some math operation on given random numbers
# Min -- returns the last number
# Max -- returns the large number
# Mean -- Mean
# Median -- Median
a1 = np.random.normal(5,1,10)
print(a1)
print("Min value = ",np.min(a1))
print("Max value = ",np.max(a1))
print("Mean value = ",np.mean(a1))
print("Median value = ",np.median(a1))

[6.81348679 4.73482125 4.6414107  4.05719936 3.59654745 5.13540428
 6.34137391 4.05313642 5.03282162 3.47715257]
Min value =  3.4771525666721166
Max value =  6.813486791074547
Mean value =  4.788335433641599
Median value =  4.688115974727198


In [12]:
a1=np.random.normal(5,1,10)
print(a1)
print('min value=',np.min(a1))
print('max value=',np.max(a1))
print('mean value=',np.mean(a1))
print('median value=',np.median(a1))

[5.78510148 5.26827536 5.6456068  4.24417709 5.78558694 3.68457947
 3.88077789 5.03906826 5.38067798 5.47919242]
min value= 3.684579465957942
max value= 5.785586935133844
mean value= 5.019304367112986
median value= 5.3244766702476


In [ ]:
c1=np.array([1,2])
c2=np.